fix  to check for PAUSED state when running startPauseReportLoop
jellyfin/jellyfin-androidtv pull request #1006
Opened 2021-07-05 19:40 UTC by dhiaayachi

**Changes**
This change is to permit startPauseReportLoop to run effectively and avoid a web socket timeout when pausing player. 

**Issues**
Fixes #400

2021-07-08 14:57 UTC, MrChip53 commented
How reliably can you reproduce issue 400?

2021-07-08 15:15 UTC, dhiaayachi commented
Hi,
I reproduce it every time I pause a video in the player for more then 5 minutes.

The behavior I observe is that the keep alive loop when paused never kick off (because of the wrong check) and I get websocket timeout log in the player.

When I play back the video it continue to play normally for the remaining of the in memory buffer before randomly jump to a timestamp earlier in the video.

2021-07-09 20:48 UTC, thornbill commented
I'm not entirely sure this will entirely fix #400, because I don't believe that check exists in 0.11.x. This is certainly an impressive find though!

2021-07-09 20:50 UTC, thornbill requested changes

2021-07-09 20:50 UTC, thornbill commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
>                      // Playback was stopped, don't report progress anymore
The comment here doesn't seem accurate.

2021-07-10 15:23 UTC, dhiaayachi commented
> I'm not sure this will entirely fix #400, because I don't believe that check exists in 0.11.x. This is certainly an impressive find though!

I did not reported #400 originally so I don't now.
I was annoyed by an issue in my setup and when I searched I found #400 and I supposed that's what I'm experiencing.
After being enough annoyed I decided to debug my self and this is how I found the issue fixed in here.
That said I'm running a debug version for few days now and I'm not experiencing the problem I noticed anymore.

The problem I'm experiencing on my fire tv is the following:
- I start a video
- after few seconds I pause it
- let it on pause for a minute or 2
- continue playing 
- after few seconds the video skip to an earlier time stamp sometimes the beginning of the video

2021-07-10 17:24 UTC, dhiaayachi commented
Is this 

> I'm not sure this will entirely fix #400, because I don't believe that check exists in 0.11.x. This is certainly an impressive find though!

I think it does, is this the code released for 0.11.x?
https://github.com/jellyfin/jellyfin-androidtv/blob/03d5b88d58bb82dc6195881dc65ded407772801c/app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java#L1008

2021-07-10 17:26 UTC, dhiaayachi commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
>                      // Playback was stopped, don't report progress anymore
Fixed

2021-07-11 09:38 UTC, nielsvanvelzen approved these changes
I'm not sure if this actually fixes #400 but the change looks like it does fix _a_ bug.

2021-07-11 14:07 UTC, dhiaayachi commented
Thank you for approving this @nielsvanvelzen 
I see this tagged for 0.12 release, do you have an ETA for it?

2021-07-11 15:00 UTC, nielsvanvelzen commented
We're aiming for a beta release in the next few weeks

2021-07-11 15:20 UTC, thornbill approved these changes

2021-07-11 15:29 UTC, merged