reworked position tracking and reporting system
jellyfin/jellyfin-androidtv pull request #1261
Opened 2021-11-20 12:30 UTC by mueslimak3r

**Changes**
1) use tmp position value for seeking instead of modifying mCurrentPosition right away
2) new method for updating mCurrentPosition. This is called not only from progressListener, but from the audio and subtitle switching methods to make sure everything is synced
3) queries to playbackController for currentPosition will return seeked position if relevant
4) seekbar will hopefully be **extra** stable now. no more jumping from 0:00 to resume position
5) adjusted directplay seeking to prevent seekbar pos irregularities

**Issues**
playbackController would report wrong position during seeking and when initializing playback
seekbar starts at 0:00 then jumps to resume position during transcode
seekbar occasionally jumped around still during seeking
Hopeful fixes for #1260 and #1239

**Other notes**
I left the debug printouts in this one so people can test it and send logs
Based on the couple issues opened since 0.12.3, this is an attempt to reassess my approach to "fixing" transcoding seeking.

2021-11-25 14:04 UTC, nielsvanvelzen requested changes
Works fine in emulator 👍

2021-11-25 14:04 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
> +    VideoManager mVideoManager = null;
Isn't it null already by default? 🤔

2021-11-25 14:04 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
> +                if (isLiveTv) { mSeekedPosition = -1;  }
```suggestion
                if (isLiveTv) mSeekedPosition = -1;
```

2021-11-25 14:04 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
> +                    else { mPlaybackState = PlaybackState.PLAYING; }
```suggestion
                    } else {
                        mPlaybackState = PlaybackState.PLAYING;
                    }
```

2021-11-26 00:02 UTC, mueslimak3r commented
fixed the formatting, and all new code I write will use the preferred formatting. I also took out the `= null`. As a C person I do that by habit but I see that java (mostly) does it for me for objects.

I also see a new issue opened: #1266 that I think may be caused by my previous "fix" for seeking. I suspect this because that change only sets `mCurrentPosition`'s value upon seek, and it is likely changed again in the `onProgressListener` before the seeking finished. In the context of the seek that occurs upon playback first starting, this could cause instability.
I haven't been able to reproduce those issues on my end, but the changes in this PR force the use of the current position to be consistent within `playbackController` and when its requested through `getCurrentPosition()`

2021-12-08 19:57 UTC, nielsvanvelzen approved these changes

2021-12-08 19:57 UTC, merged