prevent unwanted interactions with music player screensaver active
jellyfin/jellyfin-androidtv pull request #1290
Opened 2021-12-15 03:43 UTC by mueslimak3r

**Changes**
* made `KeyProcessor.createItemMenu()` public so it can be called directly, and it now returns the created menu so the caller can dismiss it
* if the created item menu is open during various events it's closed (screensaver starting, queue replaced)
* added checks for all interactive objects to account for the screensaver being active
* updated the animation for the screensaver to make the fade in and out look the same
* play/pause button is gains focus when the screensaver is stopped for user convenience

**Issues**
* the screensaver being active didn't prevent interactions with objects like the buttons or the queue items
* the dropdown menu opened by clicking on a queue item would stay open if the screensaver starts and after a queue replace (potentially deleting the clicked item from the queue)

2021-12-18 21:42 UTC, nielsvanvelzen requested changes

2021-12-18 21:42 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java
> +    private PopupMenu mPopupMenu;
```suggestion
    private PopupMenu popupMenu;
```

We don't use those c-style prefixes for variables

2021-12-18 21:42 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/AudioNowPlayingActivity.java
> +                mPopupMenu =  KeyProcessor.createItemMenu((BaseRowItem) item, ((BaseRowItem) item).getBaseItem().getUserData(), mActivity);
```suggestion
                mPopupMenu = KeyProcessor.createItemMenu((BaseRowItem) item, ((BaseRowItem) item).getBaseItem().getUserData(), mActivity);
```

2021-12-18 21:42 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/util/KeyProcessor.java
> +    // return the created PopupMenu so that the caller can dismiss it if needed
This comment doesn't seem that necessary to me. Besides, it doesn't use Javadoc/Kdoc so it's not even useful in an IDE.

2021-12-18 23:10 UTC, nielsvanvelzen approved these changes

2021-12-18 23:10 UTC, merged

2022-02-28 21:11 UTC, nielsvanvelzen commented
There is a bug report about the screensaver in the AudioNowPlayingActivity on Reddit:

https://www.reddit.com/r/jellyfin/comments/t3k3to/android_tv_beta_artist_background_bug_wmult/

I'm not 100% sure, but I think this PR might cause it. Have not been able to reproduce the issue though.

2022-03-01 00:15 UTC, mueslimak3r commented
> There is a bug report about the screensaver in the AudioNowPlayingActivity on Reddit:
> 
> https://www.reddit.com/r/jellyfin/comments/t3k3to/android_tv_beta_artist_background_bug_wmult/
> 
> I'm not 100% sure, but I think this PR might cause it. Have not been able to reproduce the issue though.
> 
> Edit: Could also be #703. I don't think we should call `setBackground` inside of rotateBackdrops because the background service already cycles between multiple backdrops.

Not much immediately stands out as potentially causing that behavior in this PR, or even in the most recent version of `nowPlayingActivity`.

The one thing that does stand out in the video as potentially related to the `nowPlayingActivity` is how right after the background switched back to the first image the time stamp jumps back from 3:23 -> 3:18.

This is done with `setCurrentTime(pos)` in the progress listener, and it's also done when starting and stopping the screensaver using `setCurrentTime(mediaManager.getValue().getCurrentAudioPosition())`
Perhaps that could give a hint on what's going on.

I'll see if I can reproduce this by adding some background photos for an artist.

wouldn't rule out #703 too