Emit JUnit output whilst running Gradle through CLI
jellyfin/jellyfin-androidtv pull request #1311
Opened 2021-12-23 13:30 UTC by DavidFair

**Changes**
Tweaks the gradle script to forward on test failures in a way that the
stack trace is preserved.

Previously, the stack pointed to a line after the test suite, e.g. line
101 on an 80 line file.

**To Test**
- Go to a test, e.g. `TimeUtilsTest` and change the expected output
- Run `gradlew test`, check the output points to the line changed

2021-12-23 15:12 UTC, nielsvanvelzen commented
Without this change the logs look somewhat like this:

```
> Task :app:testDebugUnitTest FAILED

org.jellyfin.androidtv.util.TimeUtilsTest > secondsToMillis FAILED
    java.lang.AssertionError at TimeUtilsTest.java:14
```

This seems clear enough to me, I can open TimeUtilsTest on line 14 and use the "go to declaration" command in Android Studio to open the faulty function.

With this change the log looks like this:

```
> Task :app:testDebugUnitTest FAILED

org.jellyfin.androidtv.util.TimeUtilsTest > secondsToMillis FAILED
    java.lang.AssertionError: expected:<14250> but was:<1250>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.jellyfin.androidtv.util.TimeUtilsTest.secondsToMillis(TimeUtilsTest.java:14)
```

Which is the same information as I had before but now it includes the assert functions in the stacktrace which I don't really need

2021-12-23 15:21 UTC, DavidFair commented
Sorry my test example is poor, it's exceptions that come from the code.
In `TimeUtils:secondsToMillis` add an obvious NPE:
```
        Integer foo = null;
        Integer bar = foo + 2;
        return Math.round(seconds * MILLIS_PER_SEC);
```

Without the change we get:
```
> Task :app:testDebugUnitTest FAILED

org.jellyfin.androidtv.util.TimeUtilsTest > secondsToMillis FAILED
    java.lang.NullPointerException at TimeUtilsTest.java:11

5 tests completed, 1 failed
```

With this change we get:

```
org.jellyfin.androidtv.util.TimeUtilsTest > secondsToMillis FAILED
    java.lang.NullPointerException
        at org.jellyfin.androidtv.util.TimeUtils.secondsToMillis(TimeUtils.java:28)
        at org.jellyfin.androidtv.util.TimeUtilsTest.secondsToMillis(TimeUtilsTest.java:11)

5 tests completed, 1 failed
```

Though I agree the extra noise on test failures aren't great

2021-12-26 10:34 UTC, nielsvanvelzen requested changes
Since we have multiple Gradle modules this change should be in the root build.gradle.kts instead of the app one.

2021-12-26 10:34 UTC, nielsvanvelzen commented on app/build.gradle.kts
> +        exceptionFormat = FULL
We don't use imports in our Gradle files, use the complete package instead like so:

```
exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
```

2021-12-27 08:33 UTC, nielsvanvelzen requested changes

2021-12-27 08:33 UTC, nielsvanvelzen commented on build.gradle.kts
> +			   org.gradle.api.tasks.testing.logging.TestLogEvent.SKIPPED)
```suggestion
		events(
			org.gradle.api.tasks.testing.logging.TestLogEvent.FAILED, 
			org.gradle.api.tasks.testing.logging.TestLogEvent.STANDARD_ERROR,
			org.gradle.api.tasks.testing.logging.TestLogEvent.SKIPPED
		)
```

2021-12-28 17:53 UTC, nielsvanvelzen approved these changes

2021-12-28 17:54 UTC, merged