Fix broken subtitles line wrapping after my last PR
jellyfin/jellyfin-androidtv pull request #1346
Opened 2022-01-13 13:57 UTC by siankatabg

**Changes**

Apparently I did a mistake using the ReplacementSpan for outlining the text as it doesn't support line wrapping, so lets remove it and do it with a custom TextView :)

**Issues**

2022-01-14 01:49 UTC, mueslimak3r commented
I haven't dug into the details of your implementation, so I won't comment on that yet.

But conceptually, I'm a fan of having a custom textview for outlined text. This could be used to add outlines to other UI elements that need it, like the title/clock row in the playback overlay. Currently that can be difficult to read depending on what's on screen in a video.

2022-01-14 10:01 UTC, siankatabg commented
That's exactly what I thought while doing it. Also easy to add extras as outlining colour and so on if needed at some point.

2022-01-14 17:55 UTC, nielsvanvelzen requested changes
I've not tested this or the other PR but my preference goes to a custom view like this one does. I've done a quick initial review on the code.

2022-01-14 17:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/shared/StrokeTextView.kt
> +class StrokeTextView : AppCompatTextView {
Constructor should be the same as the "ServerButtonView" class (including the overloads annotation).

2022-01-14 17:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/shared/StrokeTextView.kt
> +	private fun obtainStyledAttrs(context: Context, attrs: AttributeSet?) {
Obtaining the attributes should be similar to "ToolbarView". Get them in the `init{}` block.

2022-01-14 17:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/shared/StrokeTextView.kt
> +	// To prevent infinite call of onDraw because setTextColor calls invalidate()
Comment should be above the if-statement instead of the fun

2022-01-14 17:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/shared/StrokeTextView.kt
> +	}
Make the var public instead of this fun

2022-01-14 17:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/shared/StrokeTextView.kt
> +		if (strokeWidth > 0) {
I'd inverse the if-statement and do a return.

2022-01-16 11:23 UTC, nielsvanvelzen requested changes

2022-01-16 11:23 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/shared/StrokeTextView.kt
> +class StrokeTextView @JvmOverloads constructor(
> Constructor should be the same as the "ServerButtonView" class (including the overloads annotation).

Missing defStyleAttr

2022-01-16 11:23 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/shared/StrokeTextView.kt
> +		val styledAttrs = context.obtainStyledAttributes(attrs, R.styleable.StrokeTextView)
From linter warning:

`This TypedArray should be recycled after use with #recycle()`

2022-01-16 11:23 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/shared/StrokeTextView.kt
> +		}
```suggestion
		if (strokeWidth <= 0) return super.onDraw(canvas)

```

2022-01-16 11:23 UTC, nielsvanvelzen commented on app/src/main/res/values/attrs.xml
> +        <attr name="stroke_width" format="float" />
```suggestion
        <attr name="strokeWidth" format="float" />
```

2022-01-16 11:47 UTC, siankatabg commented
> From linter warning:
> 
> `This TypedArray should be recycled after use with #recycle()`

Sorry, I did it on a hurry yesterday and didn't even checked the warnings (the reason I didn't marked anything as resolved). But your patience and the code quality you're trying to keep in this app is amazing, thank you!

2022-01-16 13:16 UTC, mueslimak3r commented
I tested it with some videos/subtitles that clipped before and it works well!
I didn't spot any errors or find any new leaks

2022-01-16 15:07 UTC, nielsvanvelzen approved these changes

2022-01-16 15:07 UTC, merged