Add Vimu external player support and fix some MX Player issues
jellyfin/jellyfin-androidtv pull request #1719
Opened 2022-05-16 09:34 UTC by Andy2244

**Changes**
* add Vimu external player support
* add better title support on external playback
* add filename to mx player extras
* fix mPosition conversion to int
* add detection for playback completion

2022-05-24 11:01 UTC, nielsvanvelzen requested changes
The external player support is planned for removal. The existing code for it will be kept "as-is" without any new features added to it. So unfortunately we won't be merging this pull request. When the playback rewrite (#1057) is done, external player support will be entirely removed.

2022-05-24 11:18 UTC, Andy2244 commented
> When the playback rewrite (#1057) is done, external player support will be entirely removed.

@nielsvanvelzen  Yeah already heard about this from thornbill and noted my frustration on this decision.

Here are some reasons i actually need this feature:
* boxes like the Zidoo, Dune HD, Zapiti only really work correctly with the internal player and the enabled dolby VS10 engine
* in players like Vimu/Kodi you can setup live AC3 transcoding, which makes it much easier to setup a working audio playback chain, without relying on the ability to transcode audio via server
* Jellyfin does not allow transcode ogg/opus 5.1 into a AC3 5.1, there is no setting for this?
* Exoplayer does not correctly support ASS subtitles with all features
* Jellyfin has a limited way on setting/handling, audio/subtitle track selection, in contrast MX Player allows for multiple language selection and correctly handles default/forced flagged tracks

I checked Emby and even they still keep the external player option, so i wonder why would you remove a good option that seems easy to maintain?
I always liked FOSS because it gives options to users, so was expecting this from something like Plex/Emby not Jellyfin.

2022-05-24 11:48 UTC, nielsvanvelzen commented
Right now external players work (although the code is quite a hack..) but with the rewritten playback code it doesn't. So sure, merging this now is possible, but in the end it will be removed. That's why I preferred not to change it.

I'm well aware that with the current releases video playback isn't perfect. The arguments about incorrect codecs, lack of advanced substation subtitles support are all things that will be fixed in the rewritten code together with options to manually change supported codecs (and thus when transcoding will happen).

I'll review this PR and we'll merge it, but if there's any issues with it after release the PR will be reverted as I have no interest in fixing potential bugs with it.

2022-05-24 11:56 UTC, Andy2244 commented
> I'm well aware that with the current releases video playback isn't perfect.

I don't expect it to-be perfect that is the point, not even Plex manages to get to what i want. That's why i explicitly picked Jellyfin over Emby/Plex, since i can just use a external player that fixes most of my issues.

Yet as noted the biggest issue is that the default Jellyfin player will "probably" never be able to support stuff like dolby VS10. Nearly all of the streaming boxes out there, also have custom hacks/fixes in there internal player gallery3d app to circumvent issues that are specific to the chip. We also know most vendors are just too lazy to try backport those fixes to Exoplayer, so users will be left stranded and either cant use Jellyfin or must accept the hardware issues of there device.


> I'll review this PR and we'll merge it, but if there's any issues with it after release the PR will be reverted as I have no interest in fixing potential bugs with it.

Fair enough, thanks!

2022-05-24 12:02 UTC, nielsvanvelzen requested changes

2022-05-24 12:07 UTC, Andy2244 commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
> +                pos = (int) runtime; // TODO: is there a better way to indicate "finished"?
So any idea on how to simply flag watched state, my idea was just to use the fill playtime here, so i could leave the rest of the code the same?

2022-05-24 12:08 UTC, Andy2244 commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
> +            if (Objects.equals(data.getAction(), "com.mxtech.intent.result.VIEW") && resultCode == Activity.RESULT_OK && data.getStringExtra("end_by").equals("playback_completion")) { // check MX Pla
ok was just using magic strings, since the original code was already using them for the existing MX/VLC api.

2022-05-24 12:09 UTC, Andy2244 commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
> +            String filename = item.getPath().substring(item.getPath().lastIndexOf("\\") + 1);
Is there a function to directly get the filename also i'm still looking for a way to get the filesize?

2022-05-28 14:34 UTC, nielsvanvelzen approved these changes

2022-05-28 14:34 UTC, merged