Fix 'Shuffle All' for video playlist
jellyfin/jellyfin-androidtv pull request #1910
Opened 2022-07-29 17:08 UTC by kevgrig

Fixes #1712

Signed-off-by: Kevin G <kevin@myplaceonline.com>

2022-07-29 20:29 UTC, nielsvanvelzen requested changes

2022-07-29 20:29 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
> +        Timber.tag(ItemListActivity.class.getSimpleName()).d("play items: %d, shuffle: %b", items.size(), shuffle);
```suggestion
        Timber.d("play items: %d, shuffle: %b", items.size(), shuffle);
```

We never use the tag method

2022-07-29 20:32 UTC, kevgrig commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/ItemListActivity.java
> +        Timber.tag(ItemListActivity.class.getSimpleName()).d("play items: %d, shuffle: %b", items.size(), shuffle);
Updated and squashed

2022-08-01 14:06 UTC, nielsvanvelzen approved these changes

2022-08-01 20:28 UTC, kevgrig commented
Thanks for approving! I don't have authority to merge - is that something you'll do or do I need to do some other steps for this?

2022-08-02 06:49 UTC, nielsvanvelzen commented
I'll merge it when 0.14 is released. The master branch is currently frozen so we can merge critical fixes/translation updates and easily rebase the release branch on top of it.

2022-08-02 13:57 UTC, merged