Improve Android TV home screen recommendations
jellyfin/jellyfin-androidtv pull request #2515
Opened 2023-02-20 12:34 UTC by OctoNezd

**Changes**

PR introduces 3 new home screen channels:
- Latest media - new default channel
- Movies
- New episodes
![image](https://user-images.githubusercontent.com/15308404/220108963-ba6c5a9d-aa29-4e82-8409-1a6be186496e.png)

**Issues**

#2513

2023-02-20 18:08 UTC, OctoNezd commented
Also there probably should be option to make channel empty, considering that it cant be disabled at all on GoogleTV - I will implement it

2023-02-21 14:44 UTC, OctoNezd commented on app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt
> +	private fun createPreviewProgram(
I don't see how this method can be simplified or expanded into multiple ones

2023-02-26 15:51 UTC, nielsvanvelzen requested changes
Thanks for the pull request. There are two major issues that need to be changed before I can start a code review:

- Remove the "Display backdrop" option
  The backdrops are not meant to be used as thumbnails and they are not always in 16:9 aspect ratio. The Android TV launcher warps the image to fit the 16/9 ratio when the backdrop is a different size which looks awful.

- Remove "leanbackPreferredDefaultChannel" option
  There can be only one default channel and it's set when the app first starts so changing it is just not possible. Your approach to change the reported values based on the preference is a hack that I don't want to support. This is a bit unfortunate for Google TV users but there's nothing we can do about it.

2023-02-26 16:12 UTC, OctoNezd commented
1) Maybe change it to "Prefer thumbnails" instead then

2) Maybe change the default channel to something more useful than just media collections, e.g. just latest media?

2023-02-26 17:06 UTC, OctoNezd commented
> * The backdrops are not meant to be used as thumbnails and they are not always in 16:9 aspect ratio. The Android TV launcher warps the image to fit the 16/9 ratio when the backdrop is a different size which looks awful.

We can requested a cropped backdrop instead through fillHeight and fillWidth? 

In addition to:

> The backdrops are not meant to be used as thumbnails 

Jellyfin web ui calls backdrops "thumbs"
![image](https://user-images.githubusercontent.com/15308404/221425148-e2945298-04e7-4597-820a-d91a9b664486.png)

2023-03-03 19:20 UTC, nielsvanvelzen commented
> We can requested a cropped backdrop instead through fillHeight and fillWidth?

We try to use the least amount of parameters possible so we use our local image cache, so not a huge fan of this approach.

2023-03-03 19:35 UTC, OctoNezd commented
The lack of prefer backdrops option results in ugly letterboxing on gtv devices, and having it results in ugly stretching on atv then. This is a bit problematic situation, both outcomes end up in situation where one part of userbase gets screwed :/

2023-03-04 12:17 UTC, OctoNezd commented
Weird - the channel shows up for me on google tv emulator created with ADK. No next up/continue watching though. Did you add Google Account? Check if you are running apps-only mode under your google account settings. Also, apparently GTV uses channels/recommendations only in specific regions, where "the full google tv experience" is not available (cant find source for this statement, it was in some atv documentation by google).

2023-03-04 12:20 UTC, OctoNezd commented
![image](https://user-images.githubusercontent.com/15308404/222900693-4c2189a0-3d4b-4086-a00f-803f1c934e1b.png)
Here is a screenshot of gtv recommendations when using posters

2023-03-04 12:23 UTC, nielsvanvelzen commented
>  Also, apparently GTV uses channels/recommendations only in specific regions, where "the full google tv experience" is not available (cant find source for this statement, it was in some atv documentation by google).

I think this might be the issue then because I'm getting the full advertisement experience (Netherlands).

2023-03-04 12:26 UTC, OctoNezd commented
> > Also, apparently GTV uses channels/recommendations only in specific regions, where "the full google tv experience" is not available (cant find source for this statement, it was in some atv documentation by google).
> 
> I think this might be the issue then because I'm getting the full advertisement experience (Netherlands).

Yep - https://www.youtube.com/watch?v=O3BhUSEu8gg


8:51
You may have noticed home screen channels weren’t on the earlier Google TV screenshot.
8:56
For Google TV, home screen channels are only shown in markets
9:00
where we don't have enough information about content
9:02
to power the full Google TV experience.
9:05
That means they're not going to show up in markets like the US.

2023-03-18 13:26 UTC, OctoNezd commented
So - both options need to go then, I assume?

2023-03-20 16:56 UTC, nielsvanvelzen commented
Yup

2023-03-22 08:41 UTC, OctoNezd commented
All new options were removed

2023-04-04 11:32 UTC, nielsvanvelzen approved these changes
Thanks! Everything is good now. I've made some final small tweaks that you can see in the last commit.

2023-04-04 11:49 UTC, merged