Fix 4k HEVC downscaling on 1080p devices
jellyfin/jellyfin-androidtv pull request #3419
Opened 2024-02-29 17:24 UTC by MichaelRUSF

**Changes**
Add ```DeviceUtils.has4kVideoSupport``` conditional tests directly to the ```deviceHevcCodecProfile``` in the ProfileHelper. 

**Issues**
Fixes #3388  #2516

2024-03-02 02:44 UTC, MichaelRUSF commented on app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
> +				!MediaTest.supportsHevc() && !DeviceUtils.has4kVideoSupport() -> {
Copy and paste error, should have been equals.

2024-03-02 04:05 UTC, MichaelRUSF commented on app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
> +						ProfileCondition(
In theory, that statement should work, but it doesn't. Why not? Go figure. Luckily, I was able to dig up some old 1080p devices to test this out. I tried several different ways of rewriting this, but this is the version that actually worked.  

I can tell you some findings with the original code. A 4k video would transcode initially for unsupported resolution as it should.  Play another video then come back and the same file would no longer transcode and would just get remuxed causing the player to crash, along with any other video played after that. 🤷‍♂️

2024-03-03 12:13 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt
> +						ProfileCondition(
If the profile is correct the bug should be fixed server-side

2024-08-20 11:06 UTC, nielsvanvelzen requested changes
What's the current state of this change? Do we still need it or has it been fixed with one of the other profile changes already?

2024-08-21 03:26 UTC, MichaelRUSF commented
With a 2160p stream: 
```
Stream #0:0(eng): Video: hevc (Main 10), yuv420p10le(tv), 3840x1600 [SAR 1:1 DAR 12:5], 23.98 fps, 23.98 tbr, 1k tbn (default) 
``` 
The current code does not trigger a transcode and will only copy the video in its original resolution causing playback to fail for devices that do not support4k:
```
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (ac3 (native) -> aac (libfdk_aac))

Output #0, hls, to 'C:\transcode\117f45fa148a2c825ed8dd0078ab7c41.m3u8':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0: Video: hevc (Main 10) (dvh1 / 0x31687664), yuv420p10le(tv), 3840x1600 [SAR 1:1 DAR 12:5], q=2-31, 23.98 fps, 23.98 tbr, 24k tbn
```
This fix will correctly trigger a transcode to a 1080p stream:
```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> hevc (hevc_amf))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
Output #0, hls, to 'C:\transcode\f374232fd5c702c97f22ac786b736009.m3u8':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0: Video: hevc (hvc1 / 0x31637668), d3d11(tv, bt709, progressive), 1920x800 [SAR 1:1 DAR 12:5], q=2-31, 31057 kb/s, 23.98 fps, 90k tbn 
``` 

This should fix the issue described in #3820, allowing 4k to 1080p playback in Google Chromecast HD and on older 1080p firetv devices.

2024-08-21 19:57 UTC, nielsvanvelzen commented
Thanks for the explanation. I think I understand the issue now. Even before this PR the HEVC video would trigger a transcode but it wouldn't downscale the video. With these conditions added it does.

I started debugging by adding a condition for a maximum width of 100, so any video I would play would have to be transcoded. After trying various things and looking through the server code I found the issue: the server uses all codec profiles to determine if transcoding is required, but only the FIRST matching codec profile is used to set transcoding requirements.

2024-08-22 13:27 UTC, MichaelRUSF commented
Just tested out the pending server fix and it resolves the issue! This PR is no longer needed.

2024-08-22 13:27 UTC, closed without merging

2024-08-22 13:47 UTC, nielsvanvelzen commented
Awesome! Thanks for testing that. It was quite the adventure to figure out this behavior, it appears to be a side-effect from a big change in the 10.8 release.

2024-08-22 15:00 UTC, GrabbenD commented
PR: https://github.com/jellyfin/jellyfin/pull/12499

2024-08-30 16:40 UTC, avionics75 commented
Still not working with JF Server 10.9.10 and JF ATV 0.17.4, 4K content result in player error on Mi Stick 1080p with Android TV :(

FFmpeg logs : 

{"Protocol":0,"Id":"d174a83eb441d949ac7a6413bd6fbc7f","Path":"D:\\Medias\\Films\\2024\\Black.Mass.2015.MULTi.VFF.2160p.10bit.4KLight.DV.HDR.BluRay.DTS-HD.MA.5.1.x265-QTZ-Wawacity.ing.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv","Size":9409197364,"Name":"Black.Mass.2015.MULTi.VFF.2160p.10bit.4KLight.DV.HDR.BluRay.DTS-HD.MA.5.1.x265-QTZ-Wawacity.ing","IsRemote":false,"ETag":"0cb52f9c7f298f61aee84d4f795e9651","RunTimeTicks":73518860000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"hevc","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":"bt2020nc","ColorTransfer":"smpte2084","ColorPrimaries":"bt2020","DvVersionMajor":1,"DvVersionMinor":0,"DvProfile":8,"DvLevel":6,"RpuPresentFlag":1,"ElPresentFlag":0,"BlPresentFlag":1,"DvBlSignalCompatibilityId":1,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":2,"VideoRangeType":5,"VideoDoViTitle":"DV Profile 8.1 (HDR10)","AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":"4K HEVC HDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":10238676,"BitDepth":10,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1600,"Width":3840,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"Main 10","Type":1,"AspectRatio":"2.40:1","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":153,"IsAnamorphic":false},{"Codec":"ac3","CodecTag":null,"Language":"fre","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"FR VFF : AC3 5.1","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":"Par d\u00E9faut","LocalizedForced":null,"LocalizedExternal":"Externe","LocalizedHearingImpaired":null,"DisplayTitle":"FR VFF : AC3 5.1 - Fre - Dolby Digital - Par d\u00E9faut","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":"5.1","BitRate":640000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":6,"SampleRate":48000,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"dts","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"ENG VO : DTS-HD MA 5.1","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":"Par d\u00E9faut","LocalizedForced":null,"LocalizedExternal":"Externe","LocalizedHearingImpaired":null,"DisplayTitle":"ENG VO : DTS-HD MA 5.1 - Anglais","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":"5.1","BitRate":3443898,"BitDepth":24,"RefFrames":null,"PacketLength":null,"Channels":6,"SampleRate":48000,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"DTS-HD MA","Type":0,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"fre","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"FR Forced : SRT","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":"Non d\u00E9fini","LocalizedDefault":"Par d\u00E9faut","LocalizedForced":"Forc\u00E9","LocalizedExternal":"Externe","LocalizedHearingImpaired":"Malentendants","DisplayTitle":"FR Forced : SRT - Fre - Par d\u00E9faut - Forc\u00E9 - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":true,"IsHearingImpaired":false,"Height":0,"Width":0,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":3,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"fre","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"FR Full : SRT","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":"Non d\u00E9fini","LocalizedDefault":"Par d\u00E9faut","LocalizedForced":"Forc\u00E9","LocalizedExternal":"Externe","LocalizedHearingImpaired":"Malentendants","DisplayTitle":"FR Full : SRT - Fre - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":0,"Width":0,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":4,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"ENG Full : SRT","VideoRange":0,"VideoRangeType":0,"VideoDoViTitle":null,"AudioSpatialFormat":0,"LocalizedUndefined":"Non d\u00E9fini","LocalizedDefault":"Par d\u00E9faut","LocalizedForced":"Forc\u00E9","LocalizedExternal":"Externe","LocalizedHearingImpaired":"Malentendants","DisplayTitle":"ENG Full : SRT  [...]

2024-08-30 17:32 UTC, MichaelRUSF commented
@avionics75 
The client doesn't automatically detect if a device only supports 1080p. It needs to be manually listed in the `DeviceUtils.kt`. Provide your device model.

Ex
Device information
Device brand: Amazon
Device model: AFTT

```
	private const val FIRE_STICK_MODEL_GEN_1 = "AFTM"
	private const val FIRE_STICK_MODEL_GEN_2 = "AFTT"
	private const val FIRE_STICK_MODEL_GEN_3 = "AFTSSS"
```
```
	// These devices only support a max video resolution of 1080p
	fun has4kVideoSupport(): Boolean = Build.MODEL !in listOf(
		FIRE_STICK_MODEL_GEN_1,
		FIRE_STICK_MODEL_GEN_2,
		FIRE_STICK_MODEL_GEN_3,
		FIRE_STICK_LITE_MODEL,
		FIRE_TV_MODEL_GEN_1,
		FIRE_TV_MODEL_GEN_2,
		GOOGLE_CHROMECAST_HD_MODEL
	)
```

2024-08-30 21:01 UTC, avionics75 commented
Thanks for the reply ! Here are some info about the device :
Device Brand : Xiaomi
Device Name : Mi Stick
Device Model : PFJ4098EU

The model number is the one I found over the internet but i'm not sure if that's what you were talking about