Fix pcm multichannel audio for Tvs
jellyfin/jellyfin-androidtv pull request #3422
Opened 2024-03-01 19:18 UTC by MichaelRUSF

**Changes**
Android apps running on Smart TVs are limited to PCM 2.0 Audio, while DD(+) and DTS have full support. This causes multichannel formats such as AAC and Opus to output stereo audio when playing directly from a TV to a receiver. This change identifies what is a TV based on the manufacturer's name and will transcode non-DD (+)/DTS multichannel audio if the app is running on a TV.

**Issues**

Fixes  #2991  #3294  #3152  #520

2024-03-03 11:47 UTC, nielsvanvelzen requested changes
We should not introduce new behavior that relies on the manufacturer/model of the device. Use feature testing instead.

2024-03-03 14:52 UTC, MichaelRUSF commented
New tests were added based on features.

2024-03-03 18:08 UTC, nielsvanvelzen commented
If you want to know whether an audio codec is supported or not you should not test for various system features but for that specific audio codec.

2024-03-03 20:22 UTC, MichaelRUSF commented
Testing the audio codec will not work for this issue. The issue is not the lack of codec support from the TV, it’s the fact that TV apps are not allowed to output multichannel PCM, which is what Jellyfin sends for Non-DD (+)/DTS media. 

If the app is running directly from the TV, testing for Non-DD (+)/DTS codecs would come back as true if supported, but if the media is multichannel then only stereo audio will be played b/c of these limitations.

TVs can passthrough multichannel PCM from external devices plugged in via HDMI. So this is not an issue for any connected devices, e.g., Shields, Fire TVs, Chromecast, etc.

There are only two ways to solve this. Either detect if an app running from a TV and transcode multichannel PCM formats to DD, which this does. Or give users the option to bypass manually. Because automatic codec detection will not work for this issue.

2024-03-03 21:10 UTC, MichaelRUSF commented
> However all internal apps including Plex do not support lossless audio (like Dolby TrueHD) passthru, only external HDMI devices can use eArc to passthru the lossless audio formats - so those require an external media player that supports those formats. 

>There is a hardware limitation that prevents full eArc support of lossless audio codecs from the internal TV apps, this affects all current TVs not just the Sonys. eArc is only fully supported on current TVs with external HDMI devices. Internal app audio support is based on using them with streaming services that use compressed DD+ with atmos audio at maximum.

[Source](https://www.avsforum.com/threads/2021-sony-bravia-xr-a80j-oled-owners-thread-no-price-talk.3207724/page-570#post-61296846)


>If you select PCM even though you have a home theater system or soundbar connected, the sound system will only receive 2.0 channel sound and the result will not be multi-channel surround sound, even if the sound system is capable of multi-channel PCM audio.

[Source](https://www.samsung.com/us/support/answer/ANS00085244/)

2024-03-16 22:51 UTC, entropicdrifter commented
Maybe it would make more sense to just have a setting in the menu, something like a toggle to turn on transcoding of all surround (that's not already DD, DD+, or DTS) into Dolby or DTS. That'll fix AAC, OGG, TrueHD and DTS-HD MA all at once on the devices in question. 

People who don't bother to turn on the setting are probably the same people who wouldn't notice/care about the issue, right?

2024-04-26 10:39 UTC, nextlooper42 commented
Same in Kodi, there is a toggle to transcode all unsupported audio to AC3. Works like charm.

2024-08-20 11:11 UTC, nielsvanvelzen commented
What's the current state of this change? Do we still need it or has it been fixed with one of the other profile changes already?

2024-08-27 17:39 UTC, MichaelRUSF commented
Closing with new proposed PR #3936 to add a S/PDIF/ARC audio output mode. Which corresponds with the capabilities of those standards:

![image png 5886fa9dfdbdb66ab015970b4d8447a9](https://github.com/user-attachments/assets/c15223f1-95e6-4e09-a2a3-ae2aff346e99)
Source: HDMI Licensing
[Source](https://www.rtings.com/soundbar/learn/opitical-vs-hdmi)

2024-08-27 17:39 UTC, closed without merging