Blur backdrop - Preliminary implementation
jellyfin/jellyfin-androidtv pull request #3674
Opened 2024-06-13 04:58 UTC by haydenzeller

**Changes**

Add a checkbox in the Theme customization view to blur the backdrop images. Add blurBackdropEnable to UserPreferences. Add _blur to BackgroundService. Add conditional modifier in AppBackground Image() to blur using androidx.compose.ui.draw.blur.

**Issues**

2024-06-13 20:34 UTC, nielsvanvelzen commented
I don't mind adding a blur to the background, that most likely improves the design. But adding an option for it is entirely unnecessary.

2024-06-13 21:32 UTC, haydenzeller commented
Yes I agree, another menu item is rather cumbersome. I was just unsure if you wanted this feature by default or by user pref so I added it just in case. I will update my branch.

2024-06-14 20:26 UTC, nielsvanvelzen requested changes
Aside from the invalid formatting that needs to be fixed I found one issue, the server splash screen when authenticating should not be blurred.

2024-06-15 08:34 UTC, nielsvanvelzen requested changes

2024-06-15 08:34 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
> +
fix formatting

2024-06-15 08:34 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/background/AppBackground.kt
> +					)
```suggestion
					modifier = Modifier
						.fillMaxSize()
						.then(if (blurBackground) Modifier.blur(10.dp) else Modifier)
```

2024-06-16 08:40 UTC, nielsvanvelzen approved these changes
Awesome!

2024-06-16 08:44 UTC, merged

2024-08-15 10:29 UTC, acordtag commented
Hello, where does the 'enable' option appear within the Android TV interface? - cannot be seen on the 'Customization' section; it only appear the "Show backdrops" option only.

Currently running Server 10.9.9 and AndroidTV Jellyfin

2024-08-15 10:39 UTC, nielsvanvelzen commented
Background blur is always enabled on supported devices (Android 12 and newer).

2024-08-23 21:29 UTC, Antonio1637 commented
Hello. Is it possible to disable this features. I have a headache while reading text and scrolling. Blur effect is across whole screen and it does not like nice.

2024-08-24 08:02 UTC, nielsvanvelzen commented
Please open an issue for that. If there's enough demand we may add an option for it.

2025-09-13 22:25 UTC, shahribms commented
@nielsvanvelzen this should count as demand enough. referencing both issues https://github.com/jellyfin/jellyfin-androidtv/issues/4716