Add Google Chromecast HD limitation
jellyfin/jellyfin-androidtv pull request #3820
Opened 2024-08-02 12:43 UTC by majmongoose

**Changes**
Added the Google Chromecast HD to the list of devices unable to support 4K, as it reports it is capable of downscaling but is incapable of doing so in realtime. Change has been discussed with Niels in the discord.

**Note**
There still may be a bug on the jellyfin server, as the tv app is telling it to send a maximum of 1920x1080 (verified via tcpdump [TCPDump Data](https://pastebin.com/SdWGmyzP)) but it is still streaming 4k.

2024-08-02 16:51 UTC, MichaelRUSF commented
Does seem like a partial fix [#3451](https://github.com/jellyfin/jellyfin-androidtv/issues/3451). Would likely be affected by [#3388](https://github.com/jellyfin/jellyfin-androidtv/issues/3388).

2024-08-03 08:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.kt
> +	private const val GOOGLE_CHROMECAST_HD_MODEL = "Chromecast HD" // Reports to support 4K - Cannot downscale in device in realtime
```suggestion
	private const val GOOGLE_CHROMECAST_HD_MODEL = "Chromecast HD"
```

These are just constants for names, we don't specify why they exist. That's on the usage part.

2024-08-04 17:00 UTC, nielsvanvelzen requested changes

2024-08-04 17:00 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.kt
> +	val isChromecastHD: Boolean = Build.MODEL == GOOGLE_CHROMECAST_HD_MODEL
Doesn't look like this is used

2024-08-05 15:41 UTC, nielsvanvelzen approved these changes
Thanks for the PR!

2024-08-05 15:43 UTC, merged