Run LeanbackHelper onPause() to refresh home screen
jellyfin/jellyfin-androidtv pull request #4347
Opened 2024-12-27 07:48 UTC by hdweiss

**Changes**
Run LeanbackHelper onPause() to refresh home screen. When the app is paused, it is probably because the user navigated to the home screen.

**Issues**
#3139

2024-12-27 19:45 UTC, nielsvanvelzen commented
This is not a proper solution to the linked issue. The MainActivity will get paused a lot more often, like when playing a video or when opening the preferences. The worker code does quite a lot of API calls so we shouldn't spam it.

2024-12-28 10:49 UTC, hdweiss commented
That is a good point. Is there any other hook we could use or is there a way to throttle the worker?

My only idea would be to move the worker call to onStop(), so that the home row either gets updated by the periodic worker within one hour or when the TV clears the app from memory. Would that be an acceptable solution?

2024-12-28 14:23 UTC, nielsvanvelzen commented
We could maybe add an additional function to update the "next up" row only once (video-)playback finishes. The other rows shouldn't change that often so I don't think anyone will notice if those update later.

2024-12-29 08:14 UTC, hdweiss commented
According to the Android guidelines, the refresh for TV shows should happen when 1. "The user exits the app on Android TV." and 2. "The user pauses or stops playback for a piece of content for more than 5 minutes."

I have tried moving the worker call into the onStop() callback of the MainActivity, which would satisfy the first point. I have tested this and it is working perfectly on my TV.

For the second point, would this be done by listening on the PlaybackControllerNotifiable:onCompletion event?

2025-01-04 10:41 UTC, hdweiss commented
@nielsvanvelzen any chance this can get merged? While not solving the issue 100%, this small change works well enough and in practice solves it for most users.

2025-01-05 09:42 UTC, nielsvanvelzen requested changes
I'm fine with adding it to onStop. Please also update the PR title.

2025-01-05 09:42 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/browsing/MainActivity.kt
> +		val workManager by inject<WorkManager>()
Use a class property instead

2025-01-05 13:37 UTC, hdweiss commented
@nielsvanvelzen changed title and moved worker into class property

2025-01-05 14:56 UTC, nielsvanvelzen approved these changes

2025-01-05 14:56 UTC, merged