Add channel name to info row in LiveTV guide
jellyfin/jellyfin-androidtv pull request #568
Opened 2020-09-21 02:05 UTC by MrChip53

**Changes**
- Add the name of the channel in the info row for any channels that display "\<No Program Data\>"

Can this get merged and pushed to Play Store ASAP please? It's a huge QoL improvement for channels that have no EPG data in the Program Guide.

2020-09-21 07:33 UTC, nielsvanvelzen commented
@thornbill I don't have Live TV setup so unfortunately I can't test this.

@MrChip53 Thanks for you pull request. I understand you'd like to have these changes in a release as soon as possible but the current state of the app is not stable. We might be able to add this change to a patch release if we need to do any immediate bugfixing but I consider that unlikely.

2020-09-21 07:34 UTC, nielsvanvelzen approved these changes
Code looks fine

2020-09-21 13:15 UTC, MrChip53 commented
Code wise I went for the most simple implementation. If you all would prefer i can move the view creation into the helper function and rework the detailUpdate flow.

On the topic of 0.12.0, what issues are needing resolved?

2020-09-22 17:33 UTC, thornbill requested changes
I think it would be better if we could handle this in `InfoLayoutHelper.addInfoRow()` since that _should_ handle adding the channel name in the same location as when EPG data is available.

That would require some changes to the check for `mSelectedProgram.getId() != null` to be able to handle this specific case and changes to `InfoLayoutHelper.addInfoRow()` to ensure it doesn't introduce `NullPointerException`s.

2020-09-22 22:53 UTC, MrChip53 commented
I do agree. Im going to delete this pull request and start a new one in a feature branch though. Accidentally, did this in my master branch. Start adding some other tweaks and open a new one as a draft.

2020-09-23 01:13 UTC, closed without merging