Feature play with button
jellyfin/jellyfin-androidtv pull request #571
Opened 2020-09-24 18:34 UTC by okan35

Feature to choose player from the menu where we have play button. I created this because some files play fine on vlc and some play fine on external app. It is better to have such button than going to settings and changing there.

**Changes**
Added play with button next to play button. This button will only be visible if preferred player is set external app.

**Issues**
#561

2020-09-25 06:49 UTC, nielsvanvelzen requested changes
Thanks for your PR. I did an initial review on the changed code and would like to request some changes to your implementation:
- Right now the playWithButton is added when the preferred player is "External". This should be changed to a new player type called "Choose" (string: "Always ask")
- In adition, the playWithButton should replace the play button
- When a player is chosen for playback the user preferences should **not** be changed, instead only the next playing file should use the chosen player.

2020-09-25 06:49 UTC, nielsvanvelzen commented on app/src/main/res/menu/menu_details_play_with.xml
> +    <item android:title="Play with Vlc"
All titles should use strings so they can be translated.

2020-09-25 06:49 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
> +            playWithButton = new TextUnderButton(this, R.drawable.ic_add, buttonSize, 3, "Play with", new View.OnClickListener() {
"Play with" should use a string so it can be translated.

2020-09-25 06:49 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
> +                    Toast.makeText(mApplication, "Play With Button", Toast.LENGTH_SHORT).show();
This toast looks like it was intended for debugigng purposes, should probably remove it or replace it with a logger debug message.

2020-09-25 06:49 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
> +                        userPreferences.getValue().set(UserPreferences.Companion.getVideoPlayer(), PreferredVideoPlayer.VLC);
User preferences should **never** be changed without the user explicitly telling the application to do so. In this case you should find a way to set the player for the next play call without changing the setting.

2020-09-26 18:55 UTC, nielsvanvelzen requested changes
Some files have weird formatting or too many line breaks. Please check those and fix where necessary, but  try to avoid reformatting the whole file.

2020-09-26 18:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
> +		var chosenPlayer = Preference.enum("chosen_player",PreferredVideoPlayer.VLC)
Should use SystemPreferences

2020-09-26 18:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
> +                if (!isPlayerPrefChoose) {
Use `else if`

2020-09-26 18:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
> +        if (userPreferences.getValue().get(UserPreferences.Companion.getVideoPlayer()) == PreferredVideoPlayer.CHOOSE) {
Probably easier to add an `else` statement when checking if the play button should be shown

2020-09-26 18:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
> +            playWithButton = new TextUnderButton(this, R.drawable.ic_add, buttonSize, 3, getString(R.string.play_with), new View.OnClickListener() {
Since either the play or play with button is shown you can probably reuse the `playButton` property

2020-09-26 18:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
> +                                }
```suggestion
                                useVlc = preferredVideoPlayerByPlayWith == PreferredVideoPlayer.VLC;
```

2020-09-26 18:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
> +                                System.out.println("PREFERRED PLAYER " + preferredVideoPlayerByPlayWith.name());
Use `Timber` for logging

2020-09-26 18:55 UTC, nielsvanvelzen commented on app/src/main/res/values/strings.xml
> +    <string name="play_with_vlc">Play with Vlc</string>
```suggestion
    <string name="play_with_vlc">Play with libVLC</string>
```

2020-09-26 18:55 UTC, nielsvanvelzen commented on app/src/main/res/values/strings.xml
> +    <string name="play_with_exo_player">Play with Exo Player</string>
```suggestion
    <string name="play_with_exo_player">Play with ExoPlayer</string>
```

2020-09-26 18:55 UTC, nielsvanvelzen commented on app/src/main/res/values/strings.xml
> +    <string name="play_with_external_app">Play with External App</string>
```suggestion
    <string name="play_with_external_app">Play with external app</string>
```

2020-09-26 18:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
> +    PlaybackController playbackController= new  PlaybackController(MediaManager.getCurrentVideoQueue());
I think this is unused

2020-09-26 18:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
> +    PopupMenu.OnMenuItemClickListener playWithMenuListener = new PopupMenu.OnMenuItemClickListener() {
Mark private

2020-09-26 18:55 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java
> +    public PlaybackController(List<BaseItemDto> items) {
I think this is unused too

2020-10-04 10:03 UTC, nielsvanvelzen requested changes
- The "choose" option shows up for LiveTV. But I don't have LiveTV setup so I can't test if that works
- The "choose" button shows up on the artist page but music shouldn't do that

2020-10-04 10:53 UTC, okan35 commented
I haven't even seen anything related to music, So I have to check this. I also don't listen to music on jellyfin either but I believe if the page is music we don't show play with button, right ?

2020-10-04 10:55 UTC, nielsvanvelzen commented
The FullDetailsActivity is shared for pretty much everything that exists and the play with button did show up for an artist for me.

2020-10-04 11:08 UTC, okan35 commented
So basically if the current page is for music, we don't show play with button, right ?

2020-10-04 12:00 UTC, nielsvanvelzen commented
It happens now but it shouldn't

2020-10-10 14:04 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
> +            playButton = new TextUnderButton(this, R.drawable.ic_add, buttonSize, 3, getString(R.string.play_with), new View.OnClickListener() {
This one isn't fixed yet. We should use the same icon.

2020-10-18 14:11 UTC, nielsvanvelzen commented
I just tested it and it doesn't work for episodes

2020-10-18 17:01 UTC, okan35 commented
I will check it now, what exactly is not working ?

2020-10-18 17:12 UTC, nielsvanvelzen commented
The normal play button showed up in the episode page instead of the play with button

2020-10-18 17:35 UTC, nielsvanvelzen approved these changes

2020-10-18 17:39 UTC, merged