Live TV button navigations
jellyfin/jellyfin-androidtv pull request #587
Opened 2020-10-05 05:19 UTC by MrChip53

**Changes**
Change channels with number buttons on remote

**Todo**
- [ ] Channel up and down buttons
- [ ] Last channel button

**Issues**

2020-10-15 16:01 UTC, thornbill commented on app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java
> +            if (channel.getNumber().equals(number)) {
A NullPointerException is thrown here if an invalid channel number is entered.

2020-10-15 16:07 UTC, thornbill requested changes
Looks good overall. I couldn't seem to find a way to emulate the paging behavior in the emulator. I did notice entering an incorrect channel number caused an NPE. This also don't seem to be allowing "." to be entered for digital OTA channels like "3.1". I'm not sure how we should account for those channels since remotes may not have a "." button either.

2020-10-15 16:07 UTC, thornbill commented on app/src/main/java/org/jellyfin/androidtv/util/KeyUtils.kt
> +	@JvmStatic
Spacing is inconsistent in this file. I would prefer a blank line before each annotated function like was done above.

2020-10-15 18:42 UTC, MrChip53 commented
Okay im going to move this back to draft and try some things out to address the 3.1, 3.2, etc issue. I think it may require a decent rework of the channel up/down logic.

2020-10-15 19:29 UTC, PrplHaz4 commented
> 
> 
> Looks good overall. I couldn't seem to find a way to emulate the paging behavior in the emulator. I did notice entering an incorrect channel number caused an NPE. This also don't seem to be allowing "." to be entered for digital OTA channels like "3.1". I'm not sure how we should account for those channels since remotes may not have a "." button either.

Maybe this could be handled like a currency input with an applied `.` that always has one decimal place (when the channel list includes digital OTA channels).

So for channel 3 you'd enter 3-0 = 3.0, 3.1 you'd enter 3-1 = 3.1...

2020-10-15 20:53 UTC, MrChip53 commented
I think what i will look at doing is when the user inputs 3 it will have just 3 in the corner but then a drop down list with any .x channels if they exist. That way if a remote doesnt have a . button those channels will still be accessible.

2020-11-12 19:12 UTC, MrChip53 commented
Closing this for now

2020-11-12 19:12 UTC, closed without merging