Update the progress bar in FullDetailsActivity to the new design
jellyfin/jellyfin-androidtv pull request #632
Opened 2020-11-15 21:12 UTC by MrChip53

**Changes**
Updates the progress bar in the FullDetailsActivity to the new design

**Issues**

2020-11-15 21:13 UTC, MrChip53 commented
![before](https://user-images.githubusercontent.com/57076668/99196980-14d2e100-2755-11eb-80e6-600a5ce23ff0.png)
![after](https://user-images.githubusercontent.com/57076668/99196984-1ac8c200-2755-11eb-9418-5f3311407c5b.png)

Before and after images

2020-11-16 18:29 UTC, nielsvanvelzen requested changes
For series/movies/others with a logo it doesn't work properly - it should not show a progress bar on top of a logo.

2020-11-16 18:29 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/MyDetailsOverviewRow.java
> +    public void setProgress(int progress) {
```suggestion
    public void setProgress(@IntRange(from = 0, to = 100) int progress) {
```

`import androidx.annotation.IntRange;`

2020-11-17 06:26 UTC, MrChip53 commented
> For series/movies/others with a logo it doesn't work properly - it should not show a progress bar on top of a logo.

I'm not entirely sure what you mean here but I do see it is showing it for series episodes that don't actually have a main image. If this issue goes beyond that, is it reproducible on the demo server?

2020-11-17 07:56 UTC, nielsvanvelzen commented
The image shown on the details page is not always the poster/cover. If the item has a logo it will use that. You can test it by addign a logo to a series/movie in the webui and then opening it in the app.

2020-11-18 05:19 UTC, MrChip53 commented
Should be fixed now. Bad translation so Lint failed though.

2020-11-18 18:20 UTC, nielsvanvelzen requested changes

2020-11-18 18:20 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java
> +        int prog = row.getProgress();
```suggestion
        int progress = row.getProgress();
```

2020-11-18 18:20 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java
> +        if (row.getProgress() > 0  && vh.mPoster.getDrawable() != null) {
```suggestion
        if (prog/*ress*/ > 0  && vh.mPoster.getDrawable() != null) {
```

2020-11-18 18:20 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyDetailsOverviewRowPresenter.java
> +            vh.mProgress.setProgress(row.getProgress());
```suggestion
            vh.mProgress.setProgress(prog/*ress*/);
```

2020-11-18 18:20 UTC, nielsvanvelzen commented on app/src/main/res/layout/new_details_overview_row.xml
> +            android:scaleType="centerCrop"
Should keep centerInside because otherwise logo's would get cut-off

2020-11-28 18:45 UTC, nielsvanvelzen approved these changes
Code looks fine, need to test it before merging.

2020-12-15 18:40 UTC, merged