Add user images to login screen
jellyfin/jellyfin-androidtv pull request #701
Opened 2021-01-28 21:49 UTC by thornbill

**Changes**
Adds support for user images to the login screen

**Issues**
N/A

2021-01-29 18:42 UTC, nielsvanvelzen requested changes

2021-01-29 18:42 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/auth/model/AuthenticationStoreUser.kt
> +	@SerialName("primary_image_tag") val primaryImageTag: String? = null
```suggestion
	@SerialName("image_tag") val imageTag: String? = null
```

It's not like we're going to add more types of images so this makes more sense to me

2021-01-29 18:49 UTC, nielsvanvelzen commented
Turns out you don't need an image tag at all for profile pictures. The URL generated looks something like this:
`https://[jellyfin]/Users/[user-id]/Images/Primary?EnableImageEnhancers=true&MaxHeight=370`

No tag in the URL at all, so we don't need to store the tag.

2021-01-31 05:23 UTC, thornbill commented
I updated the naming of the image tag variable. As we discussed in chat, it probably makes sense to keep the tag as it's used for cache busting when the image is changed.

2021-01-31 19:08 UTC, nielsvanvelzen approved these changes

2021-01-31 19:08 UTC, merged