Manage Servers menu
jellyfin/jellyfin-androidtv pull request #713
Opened 2021-01-31 15:31 UTC by MrChip53

**Changes**

**Issues**

2021-02-03 11:04 UTC, nielsvanvelzen commented
I don't think the confirmation dialog is necessary, we've removed these kinds of dialogs from other places in the app too. When a user presses the "remove user/server" button just remove it. The "manage servers" screen could use the server address as description, additionally an "add server" button could be added. The "users screen  could use an "add user" button too, we could use the last active time as description for those users, it would also be cool if we could how profile pictures instead of the icons here. You could wrap the users in a `category {}` so they are separated from the delete server action.

2021-02-03 11:19 UTC, nielsvanvelzen requested changes

2021-02-03 11:19 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsLink.kt
> +	fun setListener(preferenceClickListener: Preference.OnPreferenceClickListener) {
I don't like the clicklistener in the `link` item. The link item is meant to link to other fragments. I think adding a new type called an "action" would be better.
You can copy the OptionsLink file to a new OptionsActions file and remove the fragment code from it and include the click listener.

2021-02-03 11:19 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/startup/StartupToolbarFragment.kt
> +			if (activity is StartupActivity) activity.manageServers()
```suggestion
			val settingsIntent = Intent(requireActivity(), PreferencesActivity::class.java)
			settingsIntent.putExtra(PreferencesActivity.EXTRA_SCREEN, ManageServersScreen::class.qualifiedName)
			startActivity(settingsIntent)
```

The fragment shouldn't depend on a specific activity (we should fix this later for the `addServer` function too)

2021-02-03 11:19 UTC, nielsvanvelzen commented on app/src/main/res/values/strings.xml
> +    <string name="lbl_manage_servers">Manage Servers</string>
```suggestion
    <string name="lbl_manage_servers">Manage servers</string>
```

2021-02-03 11:19 UTC, nielsvanvelzen commented on app/src/main/res/values/strings.xml
> +    <string name="lbl_manage_users">Users for %1$s</string>
```suggestion
    <string name="lbl_manage_users">%1$s users</string>
```

Maybe even just use the server name, not sure.

2021-02-03 11:19 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/startup/ManageServersScreen.kt
> +			link {
```suggestion
		serverMap.forEach(entry -> link {
```

Also more readable to call it "server" instead of "entry".

2021-02-03 11:19 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/startup/ManageServersScreen.kt
> +		val serverMap = authenticationStore.getServers()
```suggestion
		val servers = authenticationStore.getServers()
```

2021-02-03 11:19 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/startup/EditServerScreen.kt
> +			setTitle(R.string.lbl_remove_server)
I'd use a trash icon here. Also this one could maybe use a description like "This also removes all users"

2021-02-04 01:59 UTC, MrChip53 commented
> I don't think the confirmation dialog is necessary, we've removed these kinds of dialogs from other places in the app too. When a user presses the "remove user/server" button just remove it. The "manage servers" screen could use the server address as description, additionally an "add server" button could be added. The "users screen could use an "add user" button too, we could use the last active time as description for those users, it would also be cool if we could how profile pictures instead of the icons here. You could wrap the users in a `category {}` so they are separated from the delete server action.

I addressed everything I believe except the user images because at this time there is no way to load anything except a resource id and the add server button which I think may be big enough to justify it own PR, either by adding an edittext pref to the Options system or making the preferences be fragments on startup actvity so we can just push the addserver frag to the top when the button is clicked

2021-02-04 13:02 UTC, nielsvanvelzen requested changes
I'm wondering if we should add another menu when clicking on users to allow a few actions:

- Sign out
- Remove

We could add some more in the future like:
- Set default
- Set as service user

2021-02-04 13:02 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsAction.kt
> +class OptionsAction(
also kdoc is not correct now

2021-02-08 21:22 UTC, nielsvanvelzen requested changes

2021-02-08 21:22 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/startup/EditUserScreen.kt
> +			account?.accessToken != null -> {
Should be disabled instead of hidden when access token is not set

2021-02-08 21:22 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/startup/EditUserScreen.kt
> +			account?.accessToken != null -> {
Should use an icon/description

2021-02-08 21:22 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/startup/EditUserScreen.kt
> +			setTitle(R.string.lbl_remove)
Should use an icon/description

2021-02-08 21:22 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/startup/EditUserScreen.kt
> +				requireActivity().supportFragmentManager.fragments[0].childFragmentManager.popBackStackImmediate()
How can we be certain that the first element in `fragments` is the fragment we want to pop?

2021-02-11 15:48 UTC, nielsvanvelzen requested changes

2021-02-11 15:48 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsCategory.kt
> +
These should be extension functions in their own files (OptionsLink.kt,OptionsAction.kt). Adding _all_ functions in this file will make the code too long.

2021-02-11 15:48 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsAction.kt
> +	fun setListener(preferenceClickListener: Preference.OnPreferenceClickListener) {
Add an type alias for `Preference.OnPreferenceClickListener` so we don't leak androidx.preference classes from the DSL. Not sure if it's possible to add the typealias in the class. Extending the listener might work too if it's not final.

See https://kotlinlang.org/docs/type-aliases.html

2021-02-11 15:48 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/preference/PreferencesActivity.kt
> +		const val MAIN_PREF_TAG = "PreferencesActivity"
```suggestion
		const val FRAGMENT_TAG = "PreferencesActivity"
```

2021-02-11 15:48 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsLink.kt
> +	var extras: Bundle = bundleOf()
```suggestion
	var extras: Bundle? = null
```

2021-02-11 15:48 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsLink.kt
> +	inline fun <reified T : OptionsFragment> withFragment(extraBundle: Bundle = bundleOf()) {
```suggestion
	inline fun <reified T : OptionsFragment> withFragment(extraBundle: Bundle? = null) {
```

2021-02-11 15:48 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsLink.kt
> +			it.extras.putAll(extras)
```suggestion
			extras?.let { extras -> it.extras.putAll(extras) }
```

2021-02-11 15:48 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/preference/dsl/OptionsLink.kt
> -}
Put this one back (see other comment in OptionsCategory.kt)

2021-02-11 15:48 UTC, nielsvanvelzen commented on app/src/main/res/values/strings.xml
> +    <string name="lbl_remove_user_content">Remove this account</string>
```suggestion
    <string name="lbl_remove_user_content">Remove account</string>
```

2021-02-11 15:48 UTC, nielsvanvelzen commented on app/src/main/res/values/strings.xml
> +    <string name="lbl_sign_out_content">Sign this user out</string>
```suggestion
    <string name="lbl_sign_out_content">Sign this account out.</string>
```

2021-02-13 22:04 UTC, nielsvanvelzen approved these changes

2021-02-14 15:09 UTC, MrChip53 reviewed
Your changes LGTM @nielsvanvelzen

2021-02-23 08:13 UTC, nielsvanvelzen approved these changes

2021-02-24 16:17 UTC, thornbill requested changes
I tested this a bit and it looks great!

I did notice an issue though where I was unable to remove a server. I'm guessing this was the server that I last logged into. It seems to keep a reference to the last logged in user even after removing the server, so it doesn't actually go away.

2021-02-24 16:22 UTC, nielsvanvelzen commented
I think that behavior _should_ be fixed with #730

2021-02-24 17:08 UTC, thornbill commented
Whoops there's another conflict here now.

2021-02-25 17:50 UTC, thornbill approved these changes

2021-02-25 18:07 UTC, merged