Add the ability to hide watched/unwatched indicators on cards
jellyfin/jellyfin-androidtv pull request #741
Opened 2021-02-26 00:47 UTC by linetrimmer

**Changes**

Adds the option 'Show watched indicators' to Settings with the following choices:
- 'Always': behaves like it does now
- 'Hide unwatched count': hides the unwatched episode count from cards, keeps the watched check mark
- 'On episodes only': hides the unwatched episode count from cards, hides the watched check mark unless the item is an episode
- 'Never': hides the unwatched episode count and the watched check mark on all items

2021-03-01 03:01 UTC, thornbill commented
There are conflicts in the strings file now. :smile:

2021-03-01 04:13 UTC, linetrimmer commented
Should be good now!

2021-03-01 17:46 UTC, nielsvanvelzen requested changes

2021-03-01 17:46 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java
> +                            }
```suggestion
                            if (showIndicator == WatchedIndicatorBehavior.EPISODES_ONLY && itemDto.getBaseItemType() != BaseItemType.Episode) {
                                    mCardView.setUnwatchedCount(-1);
                             } else {
                                    mCardView.setUnwatchedCount(0);
                             }
```

Could be simplified to something like this

2021-03-01 17:46 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/presentation/MyImageCardView.java
> +        WatchedIndicatorBehavior showIndicator = get(UserPreferences.class).get(UserPreferences.Companion.getWatchedIndicatorBehavior());
I'd rather keep this class "dumb" and not lookup settings in here, would be better to add that logic to the calling side.

2021-03-05 02:56 UTC, thornbill commented on app/src/main/res/values/strings.xml
> +</resources>
You lost the trailing newline here.

2021-03-10 03:23 UTC, thornbill approved these changes

2021-03-10 03:24 UTC, merged