Display episode thumbnails on home screen, add option for series
jellyfin/jellyfin-androidtv pull request #753
Opened 2021-03-04 08:44 UTC by linetrimmer

**Changes**

- Episodes in home screen rows now use the episode specific thumbnail by default
- Adds an option to go back to using series thumbnails when available

2021-03-04 18:26 UTC, nielsvanvelzen requested changes
I'm not really sure if `seriesThumbnailsEnabled` is descriptive of the behavior but I couldn't think of any better name.

2021-03-04 18:26 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/preference/UserPreferences.kt
> +		var seriesThumbnailsEnabled = Preference.boolean("pref_enable_series_thumbnails", false)
Discussed on Matrix, should default to true

2021-03-04 18:26 UTC, nielsvanvelzen commented on app/src/main/res/values/strings.xml
> +    <string name="lbl_use_series_thumbnails_description">Use series thumbnails for episodes in home screen rows</string>
```suggestion
    <string name="lbl_use_series_thumbnails">Prefer series thumbnails</string>
    <string name="lbl_use_series_thumbnails_description">Use series thumbnails when displaying episodes</string>
```

2021-03-04 18:35 UTC, nielsvanvelzen approved these changes

2021-03-10 03:25 UTC, thornbill approved these changes
:+1: lgtm once the conflicts are resolved!

2021-03-10 17:46 UTC, thornbill approved these changes

2021-03-10 17:46 UTC, merged