Add an option to hide the chapters row
jellyfin/jellyfin-androidtv pull request #848
Opened 2021-05-02 18:17 UTC by linetrimmer

**Changes**
Adds an option to hide the chapters row on the item details screen. Since I don't extract chapter images and I never use the row, it just ends up being a rather unattractive row of teal.

Also, since it was a small change in the same file, I snuck in a commit to hide the Ends time on the item details screen if the clock is already hidden on the screen.

2021-05-02 18:57 UTC, nielsvanvelzen requested changes

2021-05-02 18:57 UTC, nielsvanvelzen commented on app/src/main/java/org/jellyfin/androidtv/ui/itemdetail/FullDetailsActivity.java
> +        boolean chaptersRowEnabled;
You can just assign it here
```suggestion
        boolean chaptersRowEnabled = userPreferences.getValue().get(UserPreferences.Companion.getChaptersRowEnabled());
```

2021-05-02 18:57 UTC, nielsvanvelzen commented on app/src/main/res/values/strings.xml
> +    <string name="lbl_show_chapters_row">Show chapters row</string>
```suggestion
    <string name="lbl_show_chapters_row">Show video chapters</string>
```

2021-05-02 18:57 UTC, nielsvanvelzen commented on app/src/main/res/values/strings.xml
> +    <string name="lbl_show_chapters_row_description">"Display the video's chapters on the item screen"</string>
```suggestion
    <string name="lbl_show_chapters_row_description">Display the video's chapters on the item details</string>
```

2021-05-05 03:14 UTC, linetrimmer commented
Hiding the end time got slightly more complicated than I initially thought it would be since I think just hiding the time leaves too much empty space. Rather than hiding the end time, it's now replaced with the writer or series network

2021-05-07 16:39 UTC, nielsvanvelzen commented
>  it's now replaced with the writer or series network

I don't like this approach, it means that instead of hiding the time (which is expected from the preference) it actually changes behavior and shows different information. What if I want that information together with the time? I think only hiding it is the solution. But...

> I think just hiding the time leaves too much empty space.

Can you explain this or share a screenshot? I don't understand what the problem with the empty space would be.

2021-05-07 18:43 UTC, linetrimmer commented
![Screenshot_1620408915](https://user-images.githubusercontent.com/46704654/117488924-f34ff680-af3a-11eb-8bb8-bb980ce13942.png)
![Screenshot_1620408976](https://user-images.githubusercontent.com/46704654/117488941-f8ad4100-af3a-11eb-9c23-a435bd102beb.png)

I think that in general a group of 3 items looks more complete than a group of 2 items, and in this case the three items frame the description section better since they connect the top of the description to the start of the buttons. This is information that's displayed on web but not on ATV, and I think displaying it makes better use of the space made available by hiding the end time. 

> What if I want that information together with the time?

There's currently not room to display the writer/network along with the end time, but there could be an option to display the information in place of the end time even if the clock is visible. Personally I lean towards there always being 3 items in that section, though.

2021-05-10 14:36 UTC, thornbill commented
I'm not sure I see the value in adding an option to hide chapters unless it is to prevent spoilers. I think that could be combined with the changes in https://github.com/jellyfin/jellyfin-androidtv/pull/850 into a single generic option to "avoid spoilers" that could be expanded to include things like descriptions in the future.

2021-07-01 21:50 UTC, linetrimmer commented
Closing in favor of #997

2021-07-01 21:50 UTC, closed without merging