Include specials when queuing subsequent episodes
jellyfin/jellyfin-androidtv pull request #851
Opened 2021-05-02 23:16 UTC by linetrimmer

**Changes**
Include specials when queuing subsequent episodes if the server is set to display specials within the seasons they aired in.

2021-05-05 17:40 UTC, ManuLinares commented
Interesting, gonna test this later.

2021-05-07 16:55 UTC, nielsvanvelzen reviewed
Everything seems to be working as expected. One thing I'm worried about though is that the next up screen does not show the season name. This can be confusing when going from a season 1 -> season 2.

2021-05-07 18:59 UTC, linetrimmer commented
It could be something like 
S1E9. The Title Titles
S3E19-20. The Title Returns
Special - The Titling

I can add these to the next up screen PR if you think they're good

2021-05-10 14:15 UTC, thornbill requested changes

2021-05-10 14:15 UTC, thornbill commented on app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
> +                                            foundMainItem = true;
This _should_ be doable with the api by setting the `StartItemId` but it seems that is not supported in the old apiclient. It maybe a good idea to add a TODO or FIXME comment here about it though.

2021-05-21 20:15 UTC, linetrimmer commented
Added the TODO for StartItemId, a check for the current user being null, and a limit for how many episodes get queued.

Went with "S{x}:E{x} - Title" and "Special - Title" for the next up screen in #850. Even without queuing subsequent seasons, it can be confusing when playing episodes by Shuffle All since the queued episodes can jump from season to season.

2021-05-25 13:51 UTC, thornbill requested changes

2021-05-25 13:51 UTC, thornbill commented on app/src/main/java/org/jellyfin/androidtv/util/apiclient/PlaybackHelper.java
> +                                    final int limit = 150; // guard against too many items - account for episodes shorter than 5 min
This limit should probably be set as a class level constant.

2021-06-09 03:56 UTC, thornbill approved these changes

2021-06-09 03:58 UTC, merged